server:
  port: 8080



spring:


  mail:
    host: smtp.163.com
    username: Lovely_Su_Su@163.com #自己的邮箱账号
    password: ZYDDNIDUXAAKANKY  #这个不是登录密码而是163授权登录的密码
    default-encoding: UTF-8
    test-connection: true
    #以下是部署到阿里云上要用到的配置！！！！！
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

  redis:
    host: 139.224.65.154
    port: 6379
    database: 0
    password: YMHlikebaby99YMHlikebaby99
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://106.14.69.227:3306/SE_now?serverTimezone=Asia/Shanghai
      username: root
      password: Db123456?

  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

  servlet:
    multipart:
      #开启上传和下载
      enabled: true
      #最大的文件大小
      max-file-size: 100MB
      #单次最大请求大小
      max-request-size: 100MB





#自定义标签，用于文件上传和下载
file:
  upload:
    disableTypes: dll,exe
    #自己开发时的测试上传文件路径
#    dir: /Users/su/test-文件上传下载实验目录/
    #docker容器中的文件路径
    dir: /courseFile






